// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4G7uMardwnFwgvlEL8QfNrXZcFUWfTP4',
    appId: '1:862705316429:web:fc5cf7791886350475a204',
    messagingSenderId: '862705316429',
    projectId: 'furniture-store-705de',
    authDomain: 'furniture-store-705de.firebaseapp.com',
    storageBucket: 'furniture-store-705de.firebasestorage.app',
    measurementId: 'G-MJTKNBPXKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnyQcirD5iF956J2gsx5rRkQ9o72eRlTc',
    appId: '1:862705316429:android:f78c71e74f85c2c475a204',
    messagingSenderId: '862705316429',
    projectId: 'furniture-store-705de',
    storageBucket: 'furniture-store-705de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdzi420oyytjji6fpcGHmj0csRIhFLNd8',
    appId: '1:862705316429:ios:2a918103d4ca048675a204',
    messagingSenderId: '862705316429',
    projectId: 'furniture-store-705de',
    storageBucket: 'furniture-store-705de.firebasestorage.app',
    iosBundleId: 'com.example.furnitureStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdzi420oyytjji6fpcGHmj0csRIhFLNd8',
    appId: '1:862705316429:ios:2a918103d4ca048675a204',
    messagingSenderId: '862705316429',
    projectId: 'furniture-store-705de',
    storageBucket: 'furniture-store-705de.firebasestorage.app',
    iosBundleId: 'com.example.furnitureStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4G7uMardwnFwgvlEL8QfNrXZcFUWfTP4',
    appId: '1:862705316429:web:66ef0ea40834d88475a204',
    messagingSenderId: '862705316429',
    projectId: 'furniture-store-705de',
    authDomain: 'furniture-store-705de.firebaseapp.com',
    storageBucket: 'furniture-store-705de.firebasestorage.app',
    measurementId: 'G-G3JYVNXWDF',
  );
}
